name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  clear-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Clear GitHub Actions Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/*.lock') }}
        run: echo "Cache cleared"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p docs
          cp -r index.html style.css script.js Assets/ docs/
          echo "const API_KEY = '${{ secrets.API_KEY }}';" >> docs/script.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./docs

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
