name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create Docs Directory
        run: mkdir -p docs

      - name: Deploy to GitHub Pages
        run: |
          cp -r index.html style.css script.js Assets/ docs/
          sed -i "s|{{API_KEY}}|${{ secrets.API_KEY }}|g" docs/script.js

          # Add the following line to print the API_KEY
          echo "API_KEY: ${{ secrets.API_KEY }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
