name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create src directory
        run: mkdir src

      - name: Use API Key in Workflow
        run: echo "const API_KEY = '${{ secrets.API_KEY }}';" > src/apikey.js
        shell: bash

      - name: Build and Deploy
        run: npm run deploy
