name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use API Key in Workflow
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Create docs directory
        run: mkdir -p docs

      - name: Deploy to GitHub Pages
        run: |
          rsync -av --exclude=docs . docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
